# Site settings
title: East Bay Robotics Society
description: >-
  East Bay Robotics Society (HBROBOTICS) - A community of robot enthusiasts 
  meeting in the San Francisco East Bay area
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # Update with your GitHub username
email: contact@hbrobotics.org

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md
  - about.md
  - meetings.md
  - contact.md

# Meeting information
meetings:
  general:
    schedule: "First Saturday of each month"
    time: "1:00 PM - 4:00 PM"
    location: "Online via Zoom"
    zoom_link: "https://zoom.us/j/your-meeting-id"
  
  sig:
    schedule: "Third Saturday of each month"
    time: "1:00 PM - 4:00 PM"
    location: "Online via Zoom"
    zoom_link: "https://zoom.us/j/your-sig-meeting-id"
  
  business:
    schedule: "Fourth Saturday of each month"
    time: "1:00 PM - 3:00 PM"
    location: "Online via Zoom"
    zoom_link: "https://zoom.us/j/your-business-meeting-id"

# Social media
github_username: hbrobotics

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
